### ISSUE TITLE
forever service service looks fine, but still not staring forever module and throwing error.

### ISSUE THREAD

**Issue by mkaliyannan** [zapty/forever-service#56]
Error: Module version mismatch. Expected 46, got 47.
    at require (internal/module.js:12:17)
    at bindings (/opt/xo-server/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/opt/xo-server/node_modules/leveldown/leveldown.js:4:46)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/xo-server/node_modules/level/level.js:1:44)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/xo-server/node_modules/level-party/index.js:1:13)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/source/xo.js:6:38)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/source/index.js:38:32)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/xo-server/index.js:11:18)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/xo-server/bin/xo-server:13:25)
error: Forever detected script exited with code: 1
error: Script restart attempt #2

**Comment by arvind-agarwal** [comment]
Looks like some issue in module you have deployed. forever-service just issues forever start command beyond that it is upto your application logic. So you will have to debug the issue, since forever seems to be running here.

**Comment by mkaliyannan** [comment]
Thanks arvind. Let me look my issues..

**Comment by mkaliyannan** [comment]
I fixed  my issue. Thanks ..
